# COORDINATES 37.7763, -122.3918

# AVAILABILITY - RIDE TYPES
ride_types_res = {'ride_types': [{'display_name': 'Lyft Line', 'pricing_details': {'base_charge': 200, 'cost_minimum': 475, 'cost_per_minute': 22, 'cost_per_mile': 121, 'currency': 'USD', 'trust_and_service': 200, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_standard.png', 'seats': 2, 'ride_type': 'lyft_line'}, {'display_name': 'Lyft', 'pricing_details': {'base_charge': 200, 'cost_minimum': 500, 'cost_per_minute': 22, 'cost_per_mile': 121, 'currency': 'USD', 'trust_and_service': 200, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_standard.png', 'seats': 4, 'ride_type': 'lyft'}, {'display_name': 'Lyft Plus', 'pricing_details': {'base_charge': 300, 'cost_minimum': 700, 'cost_per_minute': 30, 'cost_per_mile': 206, 'currency': 'USD', 'trust_and_service': 225, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 6, 'ride_type': 'lyft_plus'}, {'display_name': 'Lyft Premier', 'pricing_details': {'base_charge': 500, 'cost_minimum': 900, 'cost_per_minute': 50, 'cost_per_mile': 281, 'currency': 'USD', 'trust_and_service': 225, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 4, 'ride_type': 'lyft_premier'}, {'display_name': 'Lyft Lux', 'pricing_details': {'base_charge': 800, 'cost_minimum': 1500, 'cost_per_minute': 65, 'cost_per_mile': 381, 'currency': 'USD', 'trust_and_service': 175, 'cancel_penalty_amount': 1000}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 4, 'ride_type': 'lyft_lux'}, {'display_name': 'Lyft Lux SUV', 'pricing_details': {'base_charge': 1500, 'cost_minimum': 2500, 'cost_per_minute': 90, 'cost_per_mile': 381, 'currency': 'USD', 'trust_and_service': 175, 'cancel_penalty_amount': 1000}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 6, 'ride_type': 'lyft_luxsuv'}]}
ride_types_lyft_line_res = {'ride_types': [{'display_name': 'Lyft Line', 'pricing_details': {'base_charge': 200, 'cost_minimum': 475, 'cost_per_minute': 22, 'cost_per_mile': 121, 'currency': 'USD', 'trust_and_service': 200, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_standard.png', 'seats': 2, 'ride_type': 'lyft_line'}]}
ride_types_lyft_res = {'ride_types': [{'display_name': 'Lyft', 'pricing_details': {'base_charge': 200, 'cost_minimum': 500, 'cost_per_minute': 22, 'cost_per_mile': 121, 'currency': 'USD', 'trust_and_service': 200, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_standard.png', 'seats': 4, 'ride_type': 'lyft'}]}
ride_types_lyft_plus_res = {'ride_types': [{'display_name': 'Lyft Plus', 'pricing_details': {'base_charge': 300, 'cost_minimum': 700, 'cost_per_minute': 30, 'cost_per_mile': 206, 'currency': 'USD', 'trust_and_service': 225, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 6, 'ride_type': 'lyft_plus'}]}
ride_types_lyft_premier_res = {'ride_types': [{'display_name': 'Lyft Premier', 'pricing_details': {'base_charge': 500, 'cost_minimum': 900, 'cost_per_minute': 50, 'cost_per_mile': 281, 'currency': 'USD', 'trust_and_service': 225, 'cancel_penalty_amount': 500}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 4, 'ride_type': 'lyft_premier'}]}
ride_types_lyft_lux_res = {'ride_types': [{'display_name': 'Lyft Lux', 'pricing_details': {'base_charge': 800, 'cost_minimum': 1500, 'cost_per_minute': 65, 'cost_per_mile': 381, 'currency': 'USD', 'trust_and_service': 175, 'cancel_penalty_amount': 1000}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 4, 'ride_type': 'lyft_lux'}]}
ride_types_lyft_luxsuv_res = {'ride_types': [{'display_name': 'Lyft Lux SUV', 'pricing_details': {'base_charge': 1500, 'cost_minimum': 2500, 'cost_per_minute': 90, 'cost_per_mile': 381, 'currency': 'USD', 'trust_and_service': 175, 'cancel_penalty_amount': 1000}, 'image_url': 'https://cdn.lyft.com/assets/car_plus.png', 'seats': 6, 'ride_type': 'lyft_luxsuv'}]}
